#!/bin/sh

date
export PS4=' $SECONDS + '
set -xa

#
# obtain unique process id (pid) and make temp directories
#
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-ukmet}
export RUN=${RUN:-ukmet}

export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on SMS
# SENDDBN  - Issue DBNet Client Calls
# SENDCOM  - Copy files to /com directory
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export HOMEukmet=${HOMEukmet:-${PACKAGEROOT:?}/ukmet.${ukmet_ver}}
export SCRIPTSukmet=${SCRIPTSukmet:-$HOMEukmet/scripts}

#
# Run setpdy and initialize PDY variables
#
setpdy.sh
. ./PDY

export COMIN=${COMIN:-$(compath.py ${NET}/${ukmet_ver}/${NET}.${PDY})/gempak}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${ukmet_ver}/${NET}.${PDY})}

if [ ! -d $COMOUT ]; then
  mkdir -p -m 775 $COMOUT
fi

env

export DBN_ALERT_TYPE=UKMET_GB2

########################################################
# Execute the script.
$SCRIPTSukmet/exukmet_gdgrib2.sh
########################################################

cat $pgmout

##############################
# Remove the Temporary working directory
##############################
cd ${DATAROOT}
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
