#!/bin/sh

########################################
# Runs NAM Postprocessing up to 24 hours
########################################

# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
date
export PS4='$SECONDS + '
set -xa
#
# obtain unique process id (pid) and make temp directories
#
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-ukmet}
export RUN=${RUN:-ukmet}

export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ECFLOW
# SENDDBN  - Issue DBNet Client Calls
# SENDCOM  - Copy files to /com directory
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

#
# Set up model and cycle specific variables
#
#export DBN_ALERT_TYPE=UKMET_METAFILE
export DBN_ALERT_TYPE=UKMET_0P67_METAFILE

####################################
# Specify Execution Areas
####################################
export HOMEukmet=${HOMEukmet:-${PACKAGEROOT:?}/ukmet.${ukmet_ver}}
export EXECukmet=${EXECukmet:-$HOMEukmet/exec}
export FIXukmet=${FIXukmet:-$HOMEukmet/fix}
export USHukmet=${USHukmet:-$HOMEukmet/ush}
export SCRIPTSukmet=${SCRIPTSukmet:-$HOMEukmet/scripts}

cp $FIXukmet/datatype.tbl datatype.tbl

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY
export PDY2=`echo $PDY | cut -c3-`

#export COMIN=${COMIN:-$(compath.py -o ${NET}/${ukmet_ver}/${NET}.${PDY})/gempak}
export COMIN=${COMIN:-$(compath.py ${NET}/${ukmet_ver})}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${ukmet_ver}/${RUN}.${PDY})/gempak/meta}

export COMINgfs=${COMINgfs:-$(compath.py gfs/${gfs_ver})}
#export COMINecmwf=${COMINecmwf:-$(compath.py ecmwf/${ecmwf_ver})}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

env

msg="Begin job for $job"
postmsg "$msg"

########################################################
# Execute the META file generation scripts.
$USHukmet/ukmet_meta_us_new.sh
$USHukmet/ukmet_meta_mar_vgf.sh
$USHukmet/ukmet_meta_mar.sh
$USHukmet/ukmet_meta_mar_ver.sh
$USHukmet/ukmet_meta_ver_hpc.sh
$USHukmet/ukmet_gfs_meta_sa2.sh
########################################################

msg="job has ended"
postmsg "$jlogfile" "$msg"

cat $pgmout

##############################
# Remove the Temporary working directory
##############################
cd ${DATAROOT}
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
